name: github pages

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get -y install xsltproc docbook-xml

    - uses: actions/checkout@v2

    - name: Docbook documentation generation
      run: make -C docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/html
        force_orphan: true
